#!/usr/bin/env python3

import sys
from os import system, path
import random

#--------------GETCH-----------------------------------------------------
class _Getch:
    """Gets a single character from standard input.  Does not echo to the
screen."""
    def __init__(self):
        try:
            self.impl = _GetchWindows()
        except ImportError:
            self.impl = _GetchUnix()

    def __call__(self): return self.impl()


class _GetchUnix:
    def __init__(self):
        import tty, sys

    def __call__(self):
        import sys, tty, termios
        fd = sys.stdin.fileno()
        old_settings = termios.tcgetattr(fd)
        try:
            tty.setraw(sys.stdin.fileno())
            ch = sys.stdin.read(1)
        finally:
            termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
        return ch


class _GetchWindows:
    def __init__(self):
        import msvcrt

    def __call__(self):
        import msvcrt
        return msvcrt.getch()


getch = _Getch()
#------------------------------------------------------------------------

wordDefDict = {}
wordList = []
gameList = []

def createDictFromVocabFile():
    global wordDefDict
    global wordList
    try:
        if path.exists(sys.argv[1]):
            with open(sys.argv[1], 'r') as vocabFile:
                vocabRaw = vocabFile.read()
        else:
            raise ValueError("File not found.")
    except IndexError:
        raise IndexError("Please enter vocab file.")
    for chunks in vocabRaw.split("\n\n")[:-1]:
        info = chunks.split("\n")
        word = info[0].replace("$","")
        defs = list(filter(lambda i: i[0] == ">", info))
        defs = [i[1:] for i in defs]
        wordDefDict[word] = defs
        wordList.append(word)

def setupGame():
    global wordList
    global gameList
    start = 0
    end = len(wordList)
    try:
        start = wordList.index(sys.argv[2])
    except ValueError:
        raise ValueError("Invalid start word.")
    except IndexError:
        pass
    try:
        end = wordList.index(sys.argv[3])
        end += 1
    except ValueError:
        raise ValueError("Invalid end word.")
    except IndexError:
        pass
    gameList = wordList[start:end]

def createOptions(key):
    global wordList
    options = [key]
    while len(options) < 5:
        opt = wordList[random.randint(0, len(wordList)-1)]
        if opt not in options:
            options.append(opt)
    random.shuffle(options)
    return options

def displayResponse(key, options):
    global wordDefDict
    print(key)
    print('')
    for i in range(0, len(options)):
        print ((i+1), wordDefDict[options[i]])
    return getch()

def clearScreen():
    system("clear")

def playGame():
    global wordDefDict
    global wordList
    global gameList
    remainingWords = list(gameList)
    random.shuffle(remainingWords)
    clearScreen()
    while remainingWords:
        select = chr(0)
        key = remainingWords.pop()
        options = createOptions(key)
        selectAnswer = chr(49 + options.index(key))
        while select != selectAnswer:
            select = displayResponse(key, options)
            clearScreen()
            if select == chr(27):
                exit()

def main():
    createDictFromVocabFile()
    setupGame()
    playGame()

if __name__ == '__main__':
    main()


